name: shopping_list_app
description: Feature module for shopping list app.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
