name: chat_app
description: Feature module for chat app.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter_dotenv: ^5.2.1
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.2.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
