name: meals_app
description: Feature module for meals app.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
