name: favorite_places_app
description: Feature module for favorite places app.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  path: ^1.9.1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  http: ^1.4.0
  image_picker: ^1.1.2
  location: ^8.0.0
  google_maps_flutter: ^2.12.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
